# Generated by Django 4.1.3 on 2022-11-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_evento', models.IntegerField(verbose_name='Identificación del evento')),
                ('nombre_evento', models.CharField(max_length=300, verbose_name='Nombre del evento')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.DateTimeField(verbose_name='Hora de finalización')),
                ('lugar', models.CharField(max_length=300, verbose_name='lugar')),
                ('nombre_tallerista', models.CharField(max_length=300, verbose_name='Nombre del tallerista')),
                ('cargo', models.CharField(max_length=300, verbose_name='Cargo')),
                ('imagen', models.ImageField(upload_to='static/db', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatura', models.CharField(max_length=50, verbose_name='Signatura')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('genero', models.CharField(choices=[('infantil', 'Infantil'), ('general', 'literatura general')], max_length=50, verbose_name='Genero')),
                ('autor', models.CharField(max_length=120, verbose_name='Autor')),
                ('resena', models.CharField(max_length=1500, verbose_name='Reseña')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('unidades', models.IntegerField(verbose_name='Unidades')),
                ('imagen', models.ImageField(upload_to='static/db', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('tipo_documeto', models.CharField(choices=[('ti', 'Tarjeta identidad'), ('cc', 'Cedula'), ('ce', 'Cedula estrangeria')], max_length=50, verbose_name='Tipo documento')),
                ('identificacion', models.IntegerField(verbose_name=' Numero Identificación')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de residencia')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('municipio', models.CharField(max_length=50, verbose_name='Municipio')),
                ('user', models.CharField(max_length=70, verbose_name='usuario')),
                ('pasword', models.CharField(max_length=70, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.IntegerField(verbose_name='Codigo reserva')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Fecha_inicial', models.TimeField(verbose_name='Fecha Inicio')),
                ('Fecha_devolucion', models.TimeField(verbose_name='Fecha devolución')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuario')),
                ('signatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_prestamo', models.IntegerField(verbose_name='Codigo prestamo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Fecha_inicial', models.TimeField(verbose_name='Fecha Inicio')),
                ('Fecha_devolucion', models.TimeField(verbose_name='Fecha devolución')),
                ('identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.usuario')),
                ('signatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.libro')),
            ],
        ),
    ]
