# Generated by Django 4.1.3 on 2022-11-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_dias',
            field=models.SmallIntegerField(default=7, verbose_name='Cantidad de dias a reservar'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('infantil', 'Infantil'), ('literatura_general', 'literatura general'), ('deporte', 'Deporte'), ('economia', 'Economia'), ('matematicas', 'Matematicas'), ('secretos_para_contar', 'Secretos para Contar'), ('sexualidad', 'Sexualidad'), ('tecnologia', 'Tecnologia'), ('religion', 'Religion')], max_length=50, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_devolucion',
            field=models.DateTimeField(verbose_name='Fecha devolución'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_inicial',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Inicio'),
        ),
    ]
