# Generated by Django 4.1.3 on 2022-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_reserva_cantidad_dias_alter_libro_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_devolucion',
            field=models.DateField(verbose_name='Fecha devolución'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_inicial',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Inicio'),
        ),
    ]
