# Generated by Django 4.1.3 on 2022-11-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_reserva_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_dias',
        ),
    ]
