# Generated by Django 4.1.3 on 2022-11-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_remove_reserva_cantidad_delete_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_inicial',
            field=models.DateField(verbose_name='Fecha prestamo'),
        ),
    ]
