# Generated by Django 4.1.3 on 2022-11-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_reserva_fecha_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='Fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='Fecha_inicial',
        ),
    ]
