# Generated by Django 4.1.3 on 2022-11-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_remove_reserva_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_inicial',
            field=models.DateField(default='2022-11-15', verbose_name='Fecha prestamo'),
            preserve_default=False,
        ),
    ]
