# Generated by Django 4.1.3 on 2022-11-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_reserva_fecha_devolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='codigo_reserva',
        ),
    ]
